/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/TD/vga_wave/al_ip/DRAM.v
 ** Date	:	2022 02 24
 ** TD version	:	5.0.30786
\************************************************************/

`timescale 1ns / 1ps

module DRAM ( di, waddr, we, wclk, do, raddr );

	parameter DATA_WIDTH_W = 10; 
	parameter ADDR_WIDTH_W = 8;
	parameter DATA_DEPTH_W = 256;
	parameter DATA_WIDTH_R = 10;
	parameter ADDR_WIDTH_R = 8;
	parameter DATA_DEPTH_R = 256;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] do;



	EG_LOGIC_DRAM #(
 			.INIT_FILE("../../../mif_coe/kk256.mif"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(do),
			.raddr(raddr));

endmodule